### ISSUE TITLE
Running Rockstream on Mac OS

### ISSUE THREAD

**Issue by eyramm** [sandyh90/rockstream-streaming-relay-laravel#10]
Hello, 

Thanks for this amazing app. I'm having a few issues running this on MacOS/Linux Server

1. I set the custom path for nginx and got 

"Switch power Nginx successfuly, Nginx not found: /Users/eyramm/projects/rockstream-streaming-relay/rockstream_stream_repeater/bin/nginx"

anytime I try to start server. 

2. RTMP settings. I change the rtmp port from the default 1935 and 7734. It's either I get an error or the page loads. 

I'm not clear exactly how to run this in my environment.

**Comment by sandyh90** [comment]
Hi @eyramm 
I'm sorry about that trouble you can follow my instruction on below that maybe can help you.

### 1. Problem When Set The Custom Path Or Cannot Running.
First thing you need to change or replace the executable and configuration on the code because this app is now specially made for windows os only,  But I have already told someone step by step to change it, you can see that issue thread.

Here the references issue that same for this problem this is for linux os but i hope it can work too on Mac OS.

Reference issue:
- #2 or [Linux Config](https://github.com/sandyh90/rockstream-streaming-relay/issues/2)
- #8 or [how to install rockstream on ubuntu](https://github.com/sandyh90/rockstream-streaming-relay/issues/8)

### 2. Cannot Access The Port Or Invalid Port
Do you have already check the **.env** file or **.env.example** file first?

Because on that file there have configuration port for nginx
- ``WEB_URL_CHECKER_NGINX_RTMP_PORT=7733``
-  ``NGINX_RTMP_PORT=7734``

And after you change that configuration you need to click **Regen Config Stream [Manual]** and then click **Restart Server** or **On/Off Power** on dashboard panel.

I hope this can help you solve the problem.
