### ISSUE TITLE
how to install rockstream on ubuntu

### ISSUE THREAD

**Issue by v-7-3** [sandyh90/rockstream-streaming-relay-laravel#8]
how to install rockstream on ubuntu
pls helpe

**Comment by sandyh90** [comment]
Hi @cassahd7 , If you want to use and install this application, you can follow these steps and change the program that runs on Linux.

## 1. Update APT and current package
You need to update the apt and current package with this command below.
``sudo apt update && sudo apt upgrade`` or ``sudo apt update``

## 2. Install PHP
In this step, there are 2 types of PHP installation one for Ubuntu 20.04/18.04 and another one for Ubuntu 22.04, and for Ubuntu 20.04/18.04 you need to add Ondřej Surý PPA repository because in that version ubuntu doesn't have PHP 8.1 package but for Ubuntu 22.04 already includes the PHP 8.1 package or later.

### For Ubuntu 20.04/18.04
1. Install dependency that needs for installation
``sudo apt install lsb-release ca-certificates apt-transport-https software-properties-common -y``

2. Add Ondřej Surý PPA repository
``sudo add-apt-repository ppa:ondrej/php``

and you will get this output but you need press **Enter** to continue
```
Debian oldstable and stable packages are provided as well: https://deb.sury.org/#debian-dpa

You can get more information about the packages at https://deb.sury.org

IMPORTANT: The <foo>-backports is now required on older Ubuntu releases.

BUGS&FEATURES: This PPA now has a issue tracker:
https://deb.sury.org/#bug-reporting

CAVEATS:
1. If you are using php-gearman, you need to add ppa:ondrej/pkg-gearman
2. If you are using apache2, you are advised to add ppa:ondrej/apache2
3. If you are using nginx, you are advised to add ppa:ondrej/nginx-mainline
   or ppa:ondrej/nginx

PLEASE READ: If you like my work and want to give me a little motivation, please consider donating regularly: https://donate.sury.org/

WARNING: add-apt-repository is broken with non-UTF-8 locales, see
https://github.com/oerdnj/deb.sury.org/issues/56 for workaround:

# LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
 More info: https://launchpad.net/~ondrej/+archive/ubuntu/php
Press [ENTER] to continue or Ctrl-c to cancel adding it. <Press-Enter-Key>
```
3. Refresh and update the new packages list
``sudo apt update``

3. Install PHP package (This app need PHP 8.1 or a newer version depending new update soon)
``sudo apt install php8.1``

### For Ubuntu 22.04
In this version of ubuntu, you just have to install the PHP package without the need to add a PPA package like in Ubuntu 20.04/18.04.

1. Install PHP package (This app need PHP 8.1 or a newer version depending new update soon)
``sudo apt install php8.1``

## 3. Install NGINX + RTMP packages

1. Make sure your APT or package list on ubuntu is already updated
``sudo apt-get update``

2. Install dependency that needs for installation
``sudo apt-get install build-essential libpcre3 libpcre3-dev libssl-dev unzip``

3. Download Nginx package and Nginx RTMP package
- Nginx package
``wget http://nginx.org/download/nginx-1.22.0.tar.gz`` (example Nginx 1.22.0)

- Nginx RTMP package
``wget -O nginx-rtmp-module-master.zip https://github.com/arut/nginx-rtmp-module/archive/master.zip`` or download from Github repository [Nginx RTMP repository](https://github.com/arut/nginx-rtmp-module)

4. Extract **nginx-1.22.0.tar.gz** tar archive file with this command
``tar -zxvf nginx-1.22.0.tar.gz``

5. Unzip Nginx RTMP package zip archive with this command
``unzip nginx-rtmp-module-master.zip``

6. Change directory to the extracted NGINX source directory folder **nginx-1.22.0** with this command
``cd nginx-1.22.0``

7. Run configure command to add module and package
```
./configure \
    --add-module=../nginx-rtmp-module-master  \
    --with-http_ssl_module  \
    --with-http_realip_module \
    --with-http_addition_module \
    --with-http_sub_module \
    --with-http_dav_module \
    --with-http_flv_module \
    --with-http_mp4_module \
    --with-http_gunzip_module \
    --with-http_gzip_static_module \
    --with-http_random_index_module \
    --with-http_secure_link_module \
    --with-http_stub_status_module \
    --with-http_auth_request_module \
    --with-mail \
    --with-mail_ssl_module \
    --with-file-aio \
    --with-ipv6 \
```

8. Run **make** command to build Nginx
``make``

9. Install the build Nginx package that already made
``sudo make install`` or ``make install``

## 4. Install FFMPEG package
1. Make sure your APT or package list on ubuntu is already updated
``sudo apt-get update``

2. Install FFMpeg package
``sudo apt install ffmpeg``

## 5. Change or override executable and configuration
Before using this app, you need to change or replace the executable and configuration on the code, But I have already told someone step by step to change it, you can see the issue thread by clicking on below.

Reference issue:
#2 or [Linux Config](https://github.com/sandyh90/rockstream-streaming-relay/issues/2)

## 6. Run Built-In PHP webserver (Optional)
PHP have built-in webserver that you can use without installing additional webserver engine to run this app

1. Change directory to the this app directory folder **rockstream-stream-relay/web** or **rockstream-stream-relay-master/web** with this command
``cd rockstream-stream-relay/web``

2. Run built-in php webserver daemon
``php -S localhost:8000`` or ``php -S localhost:8000 server.php``

So that's it for how to install rockstream on ubuntu but you need to know that this app is not optimized on Linux or Ubuntu for the reason I made this on windows not on Linux but in the future I will optimize this app for Linux or Ubuntu.

### Reference:
- https://github.com/arut/nginx-rtmp-module
- https://github.com/chakkritte/nginx-rtmp-install-ubuntu
- https://github.com/sandyh90/rockstream-streaming-relay/issues/2
- https://tecadmin.net/how-to-install-php-on-ubuntu-22-04/
- https://computingforgeeks.com/how-to-install-php-on-ubuntu-linux-system/
- https://linuxize.com/post/how-to-install-ffmpeg-on-ubuntu-20-04/
- https://startutorial.com/view/fun-with-php-built-in-web-server

**Comment by sandyh90** [comment]
Feel free to open this issue if you have question again.😉
